apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: test-view
rules:
  -
    apiGroups:
      - "apps"
      - "autoscaling"
      - "batch"
      - "storage.k8s.io"
      - "rbac.authorization.k8s.io"
      - "v1"
      - "authentication.k8s.io"
      - "admissionregistration.k8s.io"
      - "apiextensions.k8s.io"
      - "extensions"
      - ""
    resources:
      - "pods"
      - "secrets"
      - "configmaps"
      - "deployments"
      - "jobs"
      - "nodes"
      - "daemonsets"
      - "replicasets"
      - "statefulsets"
      - "cronjobs"
      - "endpoints"
      - "namespaces"
      - "persistentvolumeclaims"
      - "services"
      - "storageclasses"
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: test-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-view
subjects:
- kind: ServiceAccount
  name: test-view
  namespace: default
