---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webindex
  namespace: test-tenant
  labels:
    app: centos-sts-echo
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /testvol
    type: DirectoryOrCreate
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webindex-tmpfile
  namespace: test-tenant
  labels:
    app: centos-sts-echo
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources: 
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: centos-sts-echo
  namespace: test-tenant
  labels:
    app: centos-sts-echo
spec:
  selector:
    matchLabels:
      app: centos-sts-echo
  replicas: 3
  serviceName: centos-sts-echo
  template:
    metadata:
      labels: 
        app: centos-sts-echo
    spec:
      nodeSelector:
        app: sts-nodes
      containers:
        - name: centos-sts-echo
          image: 10.6.203.60:5000/centos-base:191224
          imagePullPolicy: IfNotPresent
          env:
            - name: TMP_DIR
              value: "/tmp"
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          volumeMounts:
            - name: webindex
              mountPath: /tmp
      volumes:
      - name: webindex
        persistentVolumeClaim:
          claimName: webindex-tmpfile
